import { Link } from 'react-router-dom';
import { useLocale } from '../i18n/useLocale';
import { casinos } from '../data/casinosData';
import { localizeCasino } from '../i18n/translate';
import { guideRoutes, guideMetadata, spinTerms, withdrawalRows, paymentMethods } from '../data/topicGuides';
import GuideLinks from '../components/GuideLinks';
import '../styles/TopicGuide.css';
export default function TopicGuide(){
 const {locale,path,base}=useLocale();const en=locale==='en',i=en?1:0;const s=(pt,english)=>en?english:pt;
 const page=guideRoutes.indexOf(base);const casino=slug=>localizeCasino(casinos.find(c=>c.slug===slug),locale);
 const review=slug=><Link to={path(`/casinos/${slug}`)}>{casino(slug).name} — {s('ler análise','read review')}</Link>;
 const paragraphs=(items)=>items.map(([title,...copy])=><section className="topic-section" key={title}><h2>{title}</h2>{copy.map(p=><p key={p}>{p}</p>)}</section>);
 return <main className="topic-page"><article>
 <p className="topic-eyebrow">CasinoProsCons · {s('GUIA PRÁTICO','PRACTICAL GUIDE')} · 18+</p>
 <h1>{guideMetadata[locale][page][0]}</h1>
 <p className="topic-byline">{s('Equipa editorial CasinoProsCons · Publicado em 04/10/2026','CasinoProsCons editorial team · Published 4 October 2026')}</p>
 <GuideLinks />
 {page===0 && <>
 <p className="topic-lead">{s('Escolher um método de pagamento no casino não é apenas encontrar um logótipo conhecido. O que permite depositar pode não servir para levantar, e a rapidez do depósito diz pouco sobre o primeiro pagamento. Comece pela saída do dinheiro, antes de escolher a entrada.', 'Choosing a casino payment method means more than finding a familiar logo. A deposit method may not support withdrawals, and a fast deposit says little about the first payout. Start by checking how money comes out before deciding how it goes in.')}</p>
 <h2>{s('Comparar métodos de depósito e levantamento','Compare deposit and withdrawal methods')}</h2>
 <div className="topic-cards">{paymentMethods.map(([name,description,check])=><section className="topic-card" key={name}><h3>{name.includes(' / Bank')?s('Transferência bancária','Bank transfer'):name.includes('Cripto')?s('Criptomoedas','Cryptocurrencies'):name}</h3><p>{description[i]}</p><p><strong>{s('Antes de depositar: ','Before depositing: ')}</strong>{check[i]}</p></section>)}</div>
 {paragraphs(en?[
 ['MB WAY and Multibanco: check both sides of the transaction','Local payment names can make a cashier feel familiar. They do not tell you which route will return your funds. Ask whether withdrawals use MB WAY, a bank transfer or another supported method, and keep the answer with the payment terms.','Our Ginja review records MB WAY and Multibanco in its payment proposition. The Znaki review describes Multibanco as forthcoming instead. Because those records differ, this guide does not mark Multibanco as currently available at Ginja. Check the live cashier for your account.'],
 ['What a useful payment comparison should contain','For each method, write down the minimum deposit, minimum withdrawal, daily or monthly cap, fees, currency and verification requirements. A missing fee is not the same as a zero fee. Ask support for the applicable rule.','Do not confuse a promotion’s qualifying deposit with the cashier minimum. A small deposit can fund an account without activating the offer you intended to use.'],
 ['Choosing a method when a bonus is involved','Read the payment exclusions before accepting a promotion. Our FairPari review records that crypto deposits do not qualify for the welcome bonus. That is a bonus condition, not a statement that every crypto transaction is unavailable.','Also check whether an unfinished wagering requirement blocks withdrawal or whether requesting a payout cancels the bonus. Use the calculator to understand turnover; it cannot override payment rules.']
 ]:[
 ['MB WAY e Multibanco: confirme os dois sentidos da operação','Os nomes locais tornam a caixa familiar, mas não dizem por onde regressa o dinheiro. Pergunte se o levantamento usa MB WAY, transferência bancária ou outro método disponível, e guarde a resposta juntamente com as condições.','A nossa análise do Ginja regista MB WAY e Multibanco na proposta de pagamentos. A análise da Znaki descreve o Multibanco como uma opção futura. Como os registos divergem, este guia não assinala o Multibanco como disponível no Ginja neste momento. Confirme a caixa da sua conta.'],
 ['O que deve constar de uma comparação de pagamentos','Para cada método, anote depósito mínimo, levantamento mínimo, limite diário ou mensal, comissões, moeda e documentos exigidos. Uma comissão não indicada não equivale a uma comissão de zero euros. Peça a regra aplicável ao apoio.','Não confunda o depósito necessário para uma promoção com o mínimo da caixa. Um valor pequeno pode financiar a conta sem ativar a oferta que pretendia usar.'],
 ['Escolher o pagamento quando há um bónus','Leia as exclusões de pagamento antes de aceitar a promoção. A nossa análise da FairPari regista que os depósitos em criptomoedas não são elegíveis para o bónus de boas-vindas. É uma condição promocional, não uma afirmação de que todas as operações em cripto estão indisponíveis.','Confirme ainda se o rollover pendente impede o levantamento ou se um pedido de pagamento cancela o bónus. A calculadora ajuda a compreender o volume de apostas; não altera as regras da caixa.']])}
 <p>{review('ginja')} · {review('fairpari')}</p>
 </>}
 {page===1 && <>
 <p className="topic-lead">{s('“Em cinco minutos” pode descrever um pedido já aprovado, não o tempo desde o primeiro clique. Para comparar casinos com levantamentos rápidos, separamos o prazo publicado das condições que o tornam possível.', '“In five minutes” may describe an already approved request, not the time from your first click. To compare fast casino withdrawals, we separate published times from the conditions attached to them.')}</p>
 <section className="topic-note"><h2>{s('Como comparamos os prazos','How we compare withdrawal times')}</h2><p>{s('Só atribuímos posição quando existe um intervalo numérico na documentação consultada. Neste momento, apenas Ginja cumpre esse critério nesta seleção: a posição 1 não significa que seja mais rápido do que os restantes. Para os outros cinco, apresentamos as condições relevantes, mas ainda não temos um prazo comparável. Não é uma medição de levantamentos da nossa equipa nem altera a avaliação global dos casinos.', 'We assign a position only when a numerical range is present in the consulted documentation. At present, only Ginja meets that criterion in this selection: position 1 does not establish that it is faster than the others. For the other five, we explain the relevant conditions but do not yet have a comparable timeframe. This is not a measurement of our team’s withdrawals and does not change overall casino ratings.')}</p></section>
 <div className="topic-cards">{withdrawalRows.map(row=><section className="topic-card" key={row.slug}><p className="topic-eyebrow">{row.rank?`#${row.rank} · ${s('PRAZO PUBLICADO','PUBLISHED TIME')}`:s('FORA DA CLASSIFICAÇÃO POR TEMPO','OUTSIDE THE TIME RANKING')}</p><h2>{casino(row.slug).name}</h2><p className="topic-value">{row.time[i]}</p><p>{row.detail[i]}</p>{row.source&&<p><a href={row.source}>{row.sourceName}</a> · {s('fonte secundária, consultada em 04/10/2026','secondary source, accessed 4 October 2026')}</p>}{review(row.slug)}</section>)}</div>
 {paragraphs(en?[
 ['Approval time is not arrival time','A withdrawal can pass through a balance check, identity review, operator approval and payment processing. An instant payment method only describes part of this path. For a useful comparison, measure from the submitted request to the moment the money is usable.'],
 ['What to ask before your first withdrawal','Ask for the first-withdrawal timeframe using your exact payment method and account currency. Confirm whether it includes verification, whether it means business days and whether the amount fits the daily limit. A reply about deposits does not answer this question.'],
 ['What to do when a withdrawal is pending','Keep the request reference, submission time and applicable terms. Check the account for document requests and unresolved bonus conditions. If the quoted deadline has passed, ask support for the current stage and a case reference. Do not make another deposit simply to try to release an existing payout.'],
 ['How this comparison can become a measured ranking','A comparable test needs the method, amount, account verification state and both timestamps. One successful payout still does not establish a typical average. A useful average needs several comparable withdrawals, including requests that took longer than expected.']
 ]:[
 ['Tempo de aprovação não é tempo de chegada','Um levantamento pode passar pela análise do saldo, verificação de identidade, aprovação do operador e processamento do pagamento. Um método instantâneo descreve apenas parte desse percurso. Para uma comparação útil, conte desde o pedido até ao momento em que o dinheiro fica disponível.'],
 ['O que perguntar antes do primeiro levantamento','Peça o prazo do primeiro levantamento para o método e a moeda exatos da sua conta. Confirme se inclui verificação, se é contado em dias úteis e se o valor cabe no limite diário. Uma resposta sobre depósitos não esclarece esta questão.'],
 ['O que fazer com um levantamento pendente','Guarde a referência do pedido, a hora e as condições aplicáveis. Veja se há documentos solicitados ou requisitos de bónus pendentes. Se o prazo indicado terminou, peça ao apoio a etapa atual e uma referência de atendimento. Não faça outro depósito apenas para tentar desbloquear um pagamento existente.'],
 ['Como transformar esta comparação num ranking medido','Um teste comparável precisa do método, montante, estado de verificação e duas horas: pedido e recebimento. Um pagamento bem-sucedido ainda não estabelece uma média habitual. Uma média útil exige vários levantamentos comparáveis, incluindo os pedidos que demoraram mais do que o previsto.']])}
 </>}
 {page===2 && <>
 <p className="topic-lead">{s('Cem rodadas grátis não são cem euros. O valor de cada aposta, a slot escolhida e o requisito aplicado aos ganhos podem mudar completamente a oferta. Compare as regras antes de comparar o número no anúncio.', 'One hundred free spins are not one hundred euros. The stake per spin, selected slot and wagering on winnings can completely change the offer. Compare the rules before comparing the headline count.')}</p>
 <h2>{s('Free spins nos seis casinos analisados','Free spins at the six reviewed casinos')}</h2>
 <p>{s('Usamos as ofertas dos nossos perfis editoriais de 27/09/2026. São pacotes de boas-vindas, não uma lista de rodadas sem depósito; o mínimo apresentado é o da oferta descrita. A regra de um bónus em dinheiro não é automaticamente a regra dos ganhos das rodadas.', 'We use offers from our editorial profiles dated 27 September 2026. These are welcome packages, not a list of no-deposit spins; the minimum shown belongs to the described offer. A cash bonus rule does not automatically apply to spin winnings.')}</p>
 <div className="topic-cards">{spinTerms.map(row=><section className="topic-card" key={row.slug}><h3>{casino(row.slug).name}</h3><p className="topic-value">{row.spins} {s('rodadas grátis','free spins')}</p><p>{casino(row.slug).bonus}</p><p><strong>{s('Depósito da oferta: ','Qualifying deposit: ')}</strong>{casino(row.slug).minDeposit}</p><p>{row.note[i]}</p><p>{review(row.slug)}</p><Link className="topic-button" to={`${path('/calculadora-rollover')}?mode=spins${row.multiplier?`&multiplier=${row.multiplier}`:''}`}>{row.multiplier?s(`Calcular ganhos a ${row.multiplier}×`,`Calculate winnings at ${row.multiplier}×`):s('Calcular com a regra da minha oferta','Calculate using my offer’s rule')}</Link></section>)}</div>
 {paragraphs(en?[
 ['The stake per spin changes the comparison','A hypothetical offer of 100 spins at €0.10 provides €10 of nominal stakes. Fifty spins at €0.50 provides €25. Neither figure is a cash balance or a promised win. The result also depends on the game and the terms attached to any winnings.'],
 ['Calculate wagering on the winnings, not on the spin count','If the spins have already produced €20 and the requirement is 30× on those winnings, the qualifying turnover is €600. At 45× it is €900. At 50% game contribution, the actual betting volume doubles. These examples describe arithmetic, not a prediction of a payout.','The calculator’s free-spin mode asks for the amount actually won and the applicable multiplier. It excludes the deposit bonus so that separate requirements are not accidentally merged.'],
 ['Daily instalments and expiry','A headline package may distribute spins across deposits or daily claims. Check how many are available at each step, when they expire and which slot accepts them. Treat each instalment separately instead of assuming that the full package is credited at registration.'],
 ['Are free spins always available without a deposit?','No. Some promotions require a qualifying deposit, a claim or another eligible action. This page does not label an offer as no-deposit unless that condition is established. Before accepting any promotion, check the maximum cashout, maximum bet and treatment of unused spins.']
 ]:[
 ['O valor da aposta muda a comparação','Uma oferta hipotética de 100 rodadas a 0,10 € dá 10 € de apostas nominais. Cinquenta rodadas a 0,50 € dão 25 €. Nenhum dos valores é saldo em dinheiro nem um ganho prometido. O resultado depende também do jogo e das regras aplicadas aos ganhos.'],
 ['Calcule o rollover dos ganhos, não do número de rodadas','Se as rodadas já produziram 20 € e a regra é de 30× sobre esses ganhos, o requisito corresponde a 600 € de apostas elegíveis. A 45×, são 900 €. Com contribuição de 50%, o volume efetivamente apostado duplica. Os exemplos explicam a conta, não antecipam um pagamento.','O modo de rodadas grátis da calculadora pede o montante efetivamente ganho e o multiplicador aplicável. Exclui o bónus de depósito para não juntar requisitos que pertencem a saldos diferentes.'],
 ['Parcelas diárias e validade','Um pacote anunciado pode distribuir rodadas por depósitos ou reclamações diárias. Verifique quantas estão disponíveis em cada etapa, quando expiram e em que slot podem ser usadas. Leia cada parcela separadamente, sem assumir que o total entra na conta no registo.'],
 ['Rodadas grátis são sempre sem depósito?','Não. Algumas promoções exigem um depósito elegível, uma reclamação ou outra ação prevista nas regras. Esta página não chama sem depósito a uma oferta sem essa condição estabelecida. Antes de aceitar, confira o levantamento máximo, a aposta máxima e o destino das rodadas não utilizadas.']])}
 <p><Link className="topic-button" to={`${path('/calculadora-rollover')}?mode=spins`}>{s('Abrir calculadora de ganhos das rodadas','Open the free-spin winnings calculator')}</Link></p>
 </>}
 <section className="topic-section"><h2>{s('Fontes e critérios','Sources and criteria')}</h2><p>{s('As condições de marca remetem para as análises CasinoProsCons ligadas nesta página. Quando usamos uma fonte externa, identificamos o que ela sustenta. Não substituímos condições em conflito por uma média.', 'Brand conditions link to the CasinoProsCons reviews on this page. External sources are identified for the information they support. Conflicting conditions are not replaced with an average.')}</p>
 <ul>{(page===0?[['https://znaki.fm/pt/jogos-de-azar/metodos-de-pagamento/','Znaki — '+s('métodos de pagamento','payment methods')],['https://znaki.fm/pt/jogos-de-azar/ginja/','Znaki — Ginja']]:page===1?[['https://znaki.fm/pt/jogos-de-azar/levantamentos-rapidos/','Znaki — '+s('levantamentos rápidos','fast withdrawals')]]:[['https://znaki.fm/pt/jogos-de-azar/rodadas-gratis/','Znaki — '+s('tipos de rodadas grátis','free-spin types')]]).map(([url,label])=><li key={url}><a href={url}>{label}</a></li>)}</ul>
 <p>{s('Um método de pagamento ou um prazo curto não comprova autorização para operar em Portugal. Consulte o ', 'A payment method or short payout time does not establish authorisation to operate in Portugal. Check the ')}<a href="https://www.srij.turismodeportugal.pt/pt/jogos-e-apostas-online/entidades-licenciadas">SRIJ</a>.</p></section>
 <GuideLinks />
 </article></main>;
}
