import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useLocale } from '../i18n/useLocale';
import { calculateWagering } from '../utils/wagering';
import '../styles/WageringCalculator.css';

export default function WageringCalculator() {
  const { locale, path } = useLocale();
  const en = locale === 'en';
  const s = (pt, english) => en ? english : pt;
  const [inputs, setInputs] = useState({ deposit: '100', bonusPercent: '100', bonusCap: '', multiplier: '35', basis: 'bonus', contribution: '100', rtp: '96' });
  const [scenario, setScenario] = useState('average');
  const parsed = Object.fromEntries(Object.entries(inputs).map(([key, value]) => [key, key === 'basis' ? value : value.trim() === '' ? (key === 'bonusCap' ? null : NaN) : Number(value.replace(',', '.'))]));
  const result = calculateWagering({ ...parsed, scenario });
  const money = n => new Intl.NumberFormat(en ? 'en-IE' : 'pt-PT', { style: 'currency', currency: 'EUR', maximumFractionDigits: 2 }).format(n);
  const field = (key, label, hint) => <label className="wager-field" key={key} htmlFor={key}><span>{label}</span><input id={key} type="text" inputMode="decimal" value={inputs[key]} aria-describedby={hint ? `${key}-hint` : undefined} onChange={e => setInputs({ ...inputs, [key]: e.target.value })} />{hint && <small id={`${key}-hint`}>{hint}</small>}</label>;
  const sections = en ? [
    ['What does a 35× wagering requirement actually mean?', 'A €100 bonus with 35× wagering requires €3,500 in qualifying bets. It does not mean depositing €3,500: the same money may be staked again after a payout. Nor does it mean that €100 will last long enough to complete those bets.', 'The wording matters. If 35× applies to the deposit plus the bonus, a €100 deposit and €100 bonus require €7,000 instead. Look for the exact calculation base in the terms before comparing two offers.'],
    ['How to use the bonus calculator', 'Enter the deposit you are considering, the bonus percentage and any bonus cap. For a 100% bonus capped at €200, a €300 deposit still receives only €200. Leave the cap empty only when you want to model an uncapped offer.', 'Next, choose the wagering base, multiplier and game contribution. At 20% contribution, each €1 bet clears only €0.20 of the requirement. A €3,500 requirement therefore needs €17,500 in actual bets. At 0%, that game cannot clear a positive requirement.'],
    ['RTP estimates payouts, not your next withdrawal', 'For this tool, 96% is an editable example, not a measured market average. Use the RTP stated in the rules of the exact game version you intend to model. There is no single RTP that represents every casino game.', 'At 96% RTP, €3,500 in bets corresponds to €3,360 in theoretical cumulative payouts and €140 in expected losses. Those payouts include money repeatedly returned and staked again; they are not €3,360 of profit. Starting with €200 gives a simplified balance of €60, which is €40 below the original €100 deposit.'],
    ['Three scenarios, not three predictions', 'Average uses the entered game RTP. Lucky assumes cumulative payouts of 102% of the total stakes; Unlucky assumes 90%. These are illustrative session outcomes, not hit rates, confidence intervals or equally likely events.', 'With a €100 deposit, €100 bonus, 35× bonus-only wagering and 100% contribution, turnover stays at €3,500 in every scenario. The model balance is €270 at 102%, €60 at 96% and −€150 at 90%. The last figure is an arithmetic shortfall: the model does not simulate when the balance runs out.'],
    ['Why your actual result may be very different', 'The calculation assumes the entire turnover is completed at a constant RTP and that both deposit and bonus remain playable. It does not model stopping when the balance reaches zero. A negative model balance is an arithmetic shortfall, not a debt or a predicted account balance.', 'RTP alone cannot tell us the chance of finishing the requirement, losing the balance first or making a profit. For that, we would need the game’s payout distribution, bet size and the rules governing each balance. Even a positive model result is not a reason to expect a profitable session.'],
    ['Terms to check before accepting a bonus', 'Check the maximum permitted bet, excluded games, contribution percentages, expiry time and withdrawal cap. Also check whether the bonus is removed before withdrawal and whether cash and bonus balances are used in a particular order.', 'This calculator models a simple deposit bonus. It does not cover staged bonuses, free-spin winnings, cashback or changing game contributions. A calculated balance is not an amount the casino has agreed to pay out.'],
    ['Is a lower wagering multiplier always better?', 'Not on its own. A 25× requirement on deposit plus bonus can require more turnover than 35× on the bonus alone. Compare the euro amount, eligible games and deadline together. You can also choose to play without accepting a bonus.'],
    ['Can I calculate a guaranteed win?', 'No. The tool calculates wagering volume and an RTP-based mathematical scenario. It cannot predict a session or guarantee that you will finish wagering. Do not deposit more to chase the model’s result.']
  ] : [
    ['O que significa um rollover de 35×?', 'Um bónus de 100 € com rollover de 35× exige 3 500 € em apostas elegíveis. Não significa depositar 3 500 €: o mesmo dinheiro pode voltar a ser apostado depois de um prémio. Também não significa que os 100 € cheguem para cumprir o requisito.', 'A diferença está nas letras pequenas. Se os 35× incidirem sobre depósito e bónus, um depósito de 100 € com 100 € de bónus passa a exigir 7 000 €. Antes de comparar duas ofertas, procure nos termos a base exata do cálculo.'],
    ['Como usar a calculadora de bónus de casino', 'Introduza o depósito que pretende analisar, a percentagem do bónus e o respetivo limite. Num bónus de 100% até 200 €, depositar 300 € continua a dar apenas 200 € de bónus. Deixe o limite em branco apenas se quiser simular uma oferta sem teto.', 'Depois, escolha a base do rollover, o multiplicador e a contribuição do jogo. Com uma contribuição de 20%, cada euro apostado abate apenas 0,20 € ao requisito. Para cumprir 3 500 €, seriam necessárias apostas no total de 17 500 €. Um jogo com contribuição de 0% não permite cumprir um requisito positivo.'],
    ['O RTP estima prémios acumulados, não o próximo levantamento', 'Nesta ferramenta, 96% é um exemplo editável, não uma média de mercado medida por nós. Use o RTP indicado nas regras da versão concreta do jogo. Não existe um único valor que represente todos os jogos de casino.', 'Com RTP de 96%, 3 500 € em apostas correspondem a 3 360 € de prémios acumulados teóricos e a 140 € de perda esperada. Esses prémios incluem dinheiro que regressa ao saldo e volta a ser apostado; não são 3 360 € de lucro. Partindo de 200 €, o saldo simplificado seria 60 €: menos 40 € do que o depósito inicial de 100 €.'],
    ['Três cenários, não três previsões', 'O cenário médio usa o RTP introduzido. O sortudo assume prémios acumulados de 102% do total apostado; o azarado assume 90%. São exemplos de resultados de uma sessão, não frequências de acerto, intervalos de confiança ou acontecimentos igualmente prováveis.', 'Com 100 € de depósito, 100 € de bónus, rollover de 35× só sobre o bónus e contribuição de 100%, o volume mantém-se em 3 500 € nos três cenários. O saldo do modelo é 270 € a 102%, 60 € a 96% e −150 € a 90%. O último valor é um défice aritmético: o modelo não simula o momento em que o saldo acaba.'],
    ['Porque pode o resultado real ser muito diferente?', 'O cálculo pressupõe que todo o volume de apostas é realizado com RTP constante e que depósito e bónus estão disponíveis para jogar. Não simula a interrupção da sessão quando o saldo chega a zero. Um saldo negativo no modelo é um défice aritmético, não uma dívida nem uma previsão do saldo da conta.', 'Só com o RTP não é possível saber a probabilidade de concluir o rollover, perder o saldo antes do fim ou obter lucro. Para isso, seriam necessários a distribuição dos prémios do jogo, o valor de cada aposta e as regras de utilização dos saldos. Mesmo um resultado positivo no modelo não permite esperar uma sessão lucrativa.'],
    ['Condições a confirmar antes de aceitar um bónus', 'Verifique a aposta máxima permitida, os jogos excluídos, as percentagens de contribuição, o prazo e o limite de levantamento. Confirme também se o bónus é retirado antes do pagamento e se existe uma ordem específica para gastar saldo real e saldo de bónus.', 'Esta calculadora simula um bónus de depósito simples. Não cobre bónus por etapas, ganhos de rodadas grátis, cashback ou mudanças de contribuição entre jogos. O saldo calculado não é um montante que o casino se tenha comprometido a pagar.'],
    ['Um rollover mais baixo é sempre melhor?', 'Isoladamente, não. Um requisito de 25× sobre depósito e bónus pode exigir mais apostas do que 35× apenas sobre o bónus. Compare o montante em euros, os jogos elegíveis e o prazo em conjunto. Também pode optar por não aceitar o bónus.'],
    ['É possível calcular um ganho garantido?', 'Não. A ferramenta calcula o volume de apostas e um cenário matemático baseado no RTP. Não prevê uma sessão nem garante a conclusão do rollover. Não deposite mais dinheiro para tentar chegar ao resultado do modelo.']
  ];
  return <main className="wager-page"><article>
    <p className="wager-eyebrow">{s('GUIA E FERRAMENTA · 18+', 'GUIDE & TOOL · 18+')}</p>
    <h1>{s('Calculadora de rollover: quanto tem de apostar para cumprir um bónus?', 'Wagering calculator: how much must you bet to clear a bonus?')}</h1>
    <p className="wager-lead">{s('Um bónus de 100 € não vale o mesmo com rollover de 20× ou de 40×. Faça as contas ao volume de apostas, ajuste o RTP e veja o custo matemático do requisito antes de aceitar a oferta.', 'A €100 bonus is not the same offer at 20× and 40× wagering. Calculate the betting volume, adjust the RTP and examine the mathematical cost of the requirement before accepting an offer.')}</p>
    <p className="wager-byline">{s('Por Equipa editorial CasinoProsCons · Atualizado em 28 de setembro de 2026', 'By CasinoProsCons editorial team · Updated 28 September 2026')}</p>
    <section className="wager-tool" aria-labelledby="calculator-title"><h2 id="calculator-title">{s('Calcular requisitos de aposta e efeito do RTP', 'Calculate wagering requirements and the effect of RTP')}</h2>
      <fieldset className="wager-scenarios" aria-describedby="scenario-help"><legend>{s('Cenário de retorno', 'Return scenario')}</legend>
        {[['lucky', s('Sortudo · 102%', 'Lucky · 102%')], ['average', s('Médio · RTP introduzido', 'Average · entered RTP')], ['unlucky', s('Azarado · 90%', 'Unlucky · 90%')]].map(([value, label]) => <label key={value}><input type="radio" name="scenario" value={value} checked={scenario === value} onChange={() => setScenario(value)} />{label}</label>)}
      </fieldset>
      <p id="scenario-help" className="wager-note">{s('102% e 90% são retornos hipotéticos da sessão, não RTP dos jogos nem probabilidades de ganhar. O cenário médio usa o RTP abaixo; os outros dois mantêm uma percentagem fixa.', '102% and 90% are hypothetical session returns, not game RTPs or chances of winning. Average uses the RTP below; the other two use fixed percentages.')}</p>
      <div className="wager-inputs">
        {field('deposit', s('Depósito (€)', 'Deposit (€)'))}
        {field('bonusPercent', s('Bónus sobre o depósito (%)', 'Deposit bonus (%)'))}
        {field('bonusCap', s('Bónus máximo (€)', 'Maximum bonus (€)'), s('Em branco = sem limite no modelo.', 'Blank = no cap in the model.'))}
        {field('multiplier', s('Multiplicador de rollover (×)', 'Wagering multiplier (×)'))}
        <label className="wager-field" htmlFor="basis"><span>{s('O rollover aplica-se a', 'Wagering applies to')}</span><select id="basis" value={inputs.basis} onChange={e => setInputs({ ...inputs, basis: e.target.value })}><option value="bonus">{s('Apenas o bónus', 'Bonus only')}</option><option value="both">{s('Depósito + bónus', 'Deposit + bonus')}</option></select></label>
        {field('contribution', s('Contribuição do jogo (%)', 'Game contribution (%)'), s('Consulte os termos: nem todos os jogos contam a 100%.', 'Check the terms: not all games contribute 100%.'))}
        {field('rtp', 'RTP (%)', s('96% é um exemplo. Substitua pelo RTP do jogo.', '96% is an example. Replace it with the game’s RTP.'))}
      </div>
      <div className="wager-results" aria-live="polite" aria-atomic="true">
        {!result ? <p role="alert">{s('Preencha os campos com números válidos e não negativos. RTP e contribuição: 0–100%. Limites do modelo: depósito até 1 000 milhões, bónus até 10 000% e rollover até 10 000×.', 'Enter valid, non-negative numbers. RTP and contribution: 0–100%. Model limits: deposit up to 1 billion, bonus up to 10,000% and wagering up to 10,000×.')}</p> : <>
          <p data-testid="scenario-rate">{s('Retorno usado neste cálculo: ', 'Return used in this calculation: ')}{result.returnRate ?? (scenario === 'lucky' ? 102 : scenario === 'unlucky' ? 90 : parsed.rtp)}%</p>
          <dl><div><dt>{s('Bónus calculado', 'Calculated bonus')}</dt><dd>{money(result.bonus)}</dd></div><div><dt>{s('Requisito a cumprir', 'Qualifying wagering required')}</dt><dd>{money(result.requirement)}</dd></div>
            {!result.excluded && <><div className="wager-primary"><dt>{s('Volume total de apostas', 'Total actual betting volume')}</dt><dd data-testid="turnover">{money(result.turnover)}</dd></div><div><dt>{result.loss < 0 ? s('Ganho hipotético nas apostas', 'Hypothetical gain from betting') : scenario === 'average' ? s('Perda esperada nesse volume', 'Expected loss over that volume') : s('Perda hipotética nas apostas', 'Hypothetical loss from betting')}</dt><dd data-testid="loss">{money(Math.abs(result.loss))}</dd></div><div><dt>{s('Prémios acumulados teóricos — não é lucro', 'Theoretical cumulative payouts — not profit')}</dt><dd>{money(result.payouts)}</dd></div><div><dt>{s('Saldo do modelo após o volume completo', 'Model balance after the full turnover')}</dt><dd data-testid="balance">{money(result.balance)}</dd></div><div><dt>{s('Diferença face ao depósito inicial', 'Difference from the original deposit')}</dt><dd>{money(result.net)}</dd></div></>}
          </dl>
          {result.excluded ? <p role="alert">{s('Este jogo não contribui para o rollover. Não é possível cumprir o requisito com contribuição de 0%.', 'This game does not contribute to wagering. A positive requirement cannot be completed at 0% contribution.')}</p> : <p>{result.balance <= 0 ? s('O modelo esgota o saldo inicial ou apresenta um défice. Não interprete este valor como dívida nem como indicação para depositar mais.', 'The model exhausts the starting balance or produces a shortfall. This is neither a debt nor a suggestion to deposit more.') : s('Saldo teórico, não um levantamento previsto. Pode perder todo o saldo antes de cumprir o requisito.', 'Theoretical balance, not a predicted withdrawal. You may lose the full balance before completing wagering.')}</p>}
        </>}
      </div>
      <p className="wager-note">{s('Modelo simplificado: depósito + bónus − volume de apostas × (1 − retorno do cenário / 100). Não inclui limites de levantamento, remoção do bónus nem probabilidade de ficar sem saldo. Os valores introduzidos são calculados neste navegador.', 'Simplified model: deposit + bonus − betting volume × (1 − scenario return / 100). It excludes withdrawal caps, bonus removal and the probability of running out of funds. Inputs are calculated in this browser.')}</p>
    </section>
    <div className="wager-copy">{sections.map(([heading, ...paragraphs]) => <section key={heading}><h2>{heading}</h2>{paragraphs.map(p => <p key={p}>{p}</p>)}</section>)}
      <section><h2>{s('Fórmulas utilizadas', 'Formulas used')}</h2><ul><li>{s('Bónus = menor valor entre depósito × percentagem / 100 e limite do bónus.', 'Bonus = the lower of deposit × percentage / 100 and the bonus cap.')}</li><li>{s('Requisito = base selecionada × multiplicador.', 'Requirement = selected base × multiplier.')}</li><li>{s('Volume real = requisito ÷ (contribuição / 100).', 'Actual turnover = requirement ÷ (contribution / 100).')}</li><li>{s('Perda esperada = volume real × (1 − RTP / 100).', 'Expected loss = actual turnover × (1 − RTP / 100).')}</li></ul>
      <p>{s('Para a definição e os limites do RTP, consulte a ', 'For the definition and limitations of RTP, see the ')}<a href="https://www.gamblingcommission.gov.uk/public-and-players/guide/return-to-player-how-much-gaming-machines-payout">Gambling Commission</a>. {s('Os exemplos são hipotéticos e não descrevem uma oferta específica.', 'Examples are hypothetical and do not describe a specific offer.')}</p></section>
      <p><Link to={path('/bonuses')}>{s('Comparar condições dos bónus de casino', 'Compare casino bonus conditions')}</Link> · <Link to={path('/casinos')}>{s('Consultar análises de casinos', 'Read casino reviews')}</Link></p>
    </div>
  </article></main>;
}
